### ISSUE TITLE
Zaprojektowanie struktury Bazy Danych

### ISSUE THREAD

**Issue by J-Dusza** [Sapiejewski/Trip-split#4]
Trzeba wymyślić jakie typy (finalnie modele) będziemy mieli w bazie danych i umieścić w tym issue. Na pewno muszą się znaleźć

- Wyjazdy
- Osoby

Dobrze byłoby to rozpisać i jakie relacje mamy pomiędzy modelami

**Comment by J-Dusza** [comment]
Django domyślnie współpracuje z SQLite więc myślę że może to być łatwiejsze w implementacji niż mongo. Ma domyślnie też orm do tego sqlite

**Comment by Bauero** [comment]
Jak na razie wydaje nam się że udało się tobie Janku to dobrze zimplementować, dlatego zamykam to issue
